#!/usr/bin/env python3
"""Convert a PNG image to an LVGL A8 (alpha-only) C source file.

Usage:
    python3 tools/png_to_lvgl_a8.py <input.png> <output.c> <variable_name>

The script extracts the alpha channel from an RGBA PNG and writes it as
a const uint8_t array with an lv_image_dsc_t descriptor, suitable for
use with LV_COLOR_FORMAT_A8 in LVGL v9.

The image can then be displayed with lv_image and recolored to any
desired foreground color (e.g., white on a black background).
"""

import sys
from PIL import Image


def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <input.png> <output.c> <variable_name>")
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]
    var_name = sys.argv[3]

    img = Image.open(input_path).convert("RGBA")
    width, height = img.size
    alpha = img.split()[3]  # Extract alpha channel
    data = list(alpha.getdata())

    data_size = width * height

    with open(output_path, "w") as f:
        f.write("/* Auto-generated by tools/png_to_lvgl_a8.py — do not edit */\n")
        f.write('#include "lvgl.h"\n\n')

        # Write alpha data array
        f.write(f"static const uint8_t {var_name}_data[{data_size}] = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            f.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write("};\n\n")

        # Write image descriptor
        f.write(f"const lv_image_dsc_t {var_name} = {{\n")
        f.write("    .header = {\n")
        f.write("        .magic = LV_IMAGE_HEADER_MAGIC,\n")
        f.write(f"        .cf    = LV_COLOR_FORMAT_A8,\n")
        f.write(f"        .w     = {width},\n")
        f.write(f"        .h     = {height},\n")
        f.write(f"        .stride = {width},\n")
        f.write("    },\n")
        f.write(f"    .data_size = {data_size},\n")
        f.write(f"    .data      = {var_name}_data,\n")
        f.write("};\n")

    print(f"Generated {output_path}: {width}x{height} A8 ({data_size} bytes)")


if __name__ == "__main__":
    main()
